spring.application.name=creator-settlement-api

spring.datasource.url=jdbc:postgresql://localhost:5433/settlement_db
spring.datasource.username=test
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.liveklass.assignment
mybatis.configuration.map-underscore-to-camel-case=true

# MyBatis SQL 로그
logging.level.com.liveklass.assignment=DEBUG
logging.level.org.mybatis=DEBUG
logging.level.java.sql=DEBUG
logging.level.jdbc.sqlonly=DEBUG

# MyBatis 실행 SQL 출력
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl