CREATE TABLE creator (
    creator_id VARCHAR(50) NOT NULL,
    creator_nm VARCHAR(50) NOT NULL,
    platform_commission INT NOT NULL,
    PRIMARY KEY (creator_id)
);

CREATE TABLE course (
    course_id VARCHAR(50) NOT NULL,
    creator_id VARCHAR(50) NOT NULL,
    course_title VARCHAR(50) NOT NULL,
    course_price BIGINT NOT NULL,
    PRIMARY KEY (course_id)
);

CREATE TABLE sale_record (
    sale_serl_num BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_num VARCHAR(50) NOT NULL,
    course_id VARCHAR(50) NOT NULL,
    student_id VARCHAR(50) NOT NULL,
    amount BIGINT NOT NULL,
    sale_status VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (sale_serl_num)
);

CREATE UNIQUE INDEX sale_uk ON sale_record (sale_num, sale_status);